### ISSUE TITLE
Lynx black screen

### ISSUE THREAD

**Issue by DrBuns3n** [retro-esp32/RetroESP32#52]
Tried Batman Returns and Stun Runner in the Lynx emulator (RetroESP32 1.9) and both start to black screen. Switch off Odroid Go and back on again and the game displays ok, but screen brightness is at minimum. Menu brightness change option is not available.

**Comment by EduOrtegaDEV** [comment]
Same problem here, I just created a ticket:

https://github.com/retro-esp32/RetroESP32/issues/54

**Comment by ultrasteveg** [comment]
Confirmed to have exactly the same issue when using v2.0

**Comment by 32teeth** [comment]
Resolved in [v.2.1](https://github.com/retro-esp32/RetroESP32/releases/tag/v.2.1-NES%2BLYNX)

**Comment by ultrasteveg** [comment]
Not resolved for me in v2.1 - have posted a video link in comment on other ticket.

**Comment by EduOrtegaDEV** [comment]
Me neither, screen still turning off when selecting an Atari Lynx game.

**Comment by EduOrtegaDEV** [comment]
Solved in v2.2
