### ISSUE TITLE
Screen turns off when selecting Atari Lynx game

### ISSUE THREAD

**Issue by EduOrtegaDEV** [retro-esp32/RetroESP32#54]
**Describe the bug**
Once I select an Atari Lynx game the screen turns off.

**To Reproduce**
1. Go to 'Atari Lynx'
2. Select a game
3. See error

**Expected behavior**
The game launches correctly.

**Screenshots**
You can see a video here: https://drive.google.com/open?id=121NM-n6VXreRm_kneZ295M7Dw4pT_3GG

**Additional context**
I have version 1.9 installed.
77 games on Atari Lynx emulator.
More than 300 games in the SD.
Using a Odroid GO.
I tried with GameBoy, NES, and GameBoy Color games and these emulators are working OK.

**Comment by 32teeth** [comment]
Resolved in [v.2.1](https://github.com/retro-esp32/RetroESP32/releases/tag/v.2.1-NES%2BLYNX)

**Comment by ultrasteveg** [comment]
Issue is still present for me running v2.1

Video here: https://drive.google.com/open?id=1jszKU40C81zTbIfQPjMhjgy95ZYeQok7

**Comment by EduOrtegaDEV** [comment]
Not solved, still present in v2.1

**Comment by EduOrtegaDEV** [comment]
Solved in v2.2
